### ISSUE TITLE
Preview Bridge (Image) can't open Mask Editor

### ISSUE THREAD

**Issue by edicam** [ltdrdata/ComfyUI-Impact-Pack#1155]
After last updates the Mask Editor can't be opened from Preview Bridge (Image).
The Mask Editor works normally when launched from other nodes, like Load Image.
Usually the Preview Bridge node create 4 images in the "input/clipspace" when receiving a new image. These images are not being created anymore.

Tested on a fresh install, with only Manager, Impact (8.28.0) and Inspire (1.23.0) installed.

ComfyUI 0.3.76
ComfyUI_frontend v1.33.10
ComfyUI-Manager V3.37.2

System Info OS win32
Python Version 3.13.6 (tags/v3.13.6:4e66535, Aug 6 2025, 14:36:00) [MSC v.1944 64 bit (AMD64)]
Embedded Python true
Pytorch Version 2.8.0+cu129
Arguments ComfyUI\main.py --windows-standalone-build
RAM Total 95.87 GB
RAM Free 84.58 GB
Devices
Name cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Type cuda
VRAM Total 24 GB
VRAM Free 19.95 GB
Torch VRAM Total 0 B
Torch VRAM Free 0 B

**Comment by tester4488** [comment]
with comfyui-frontend-package==1.33.10 open in mask editor in Preview bridge (image) dont work.
back to comfyui-frontend-package==1.32.10

**Comment by asagi4** [comment]
Looking at the developer console, it seems it tries to open an image using the weird "$1-0" placeholder value as a filename.

I don't know what's going on with that placeholder or why it would suddenly not work, but I would guess there's some hook in the javascript code for Preview Bridge that no longer works properly.

**Comment by zslefour** [comment]
> 看开发者控制台，似乎它试图用奇怪的“$1-0”占位符作为文件名打开图片。
> 
> 我不知道那个占位符到底怎么回事，为什么突然失效，但我猜 Preview Bridge 的 JavaScript 代码里有某个钩子已经无法正常工作了。

我的是“$6-0"

**Comment by zslefour** [comment]
> with comfyui-frontend-package==1.33.10 open in mask editor in Preview bridge (image) dont work. back to comfyui-frontend-package==1.32.10

However, each time the workflow needs to be refreshed before masking can be done on a new image.

**Comment by rocky533** [comment]
Is there a fix for this, I use this often.

**Comment by edicam** [comment]
Fixed with 
ComfyUI 0.3.77
and
ComfyUI_frontend v1.32.10 << downgrade

**Comment by asagi4** [comment]
Downgrading isn't a fix. This bug still exists. 1.32.10 isn't supported by current ComfyUI versions (though it still works)
