### ISSUE TITLE
Preview Bridge: Mask editor broken

### ISSUE THREAD

**Issue by flyingshutter** [ltdrdata/ComfyUI-Impact-Pack#1157]
**Update 2025-01-23**
Closing issue, latest ComfyUI release v0.10.0 uses frontend version v1.36.14
Mask editor works agein.

**Update 2025-12-31**
> The issue is solved with ComfyUI_frontend v1.37.1
> ComfyUI master is using 1.35.9
> 
> I will close the issue when master is on >=v1.37.1
> 
> (if you are affected and want to have the latest frontend version, add
> --front-end-version Comfy-Org/ComfyUI_frontend@latest
> to your ComfyUI Launch script)

**Original description:**
The "mask editor | Image Canvas" is not working for both image and latent Preview Bridge.

Example:
<img width="1171" height="464" alt="Image" src="https://github.com/user-attachments/assets/a6a3973c-4219-4eae-9cb6-acd066c27266" />

<img width="377" height="516" alt="Image" src="https://github.com/user-attachments/assets/27e2af1b-c871-4fd2-8994-2d8bb2aba848" />

On the standard "Load Image", the mask editor works just fine.

ComfyUI 0.3.76     ComfyUI_frontend v1.33.10      standalone with embedded python
ComfyUI Impact Pack 8.28.0

**Comment by alexopus** [comment]
I have a similar issue, which could be related.
For me it always opens the New Mask Editor, even though this setting is off:
<img width="744" height="89" alt="Image" src="https://github.com/user-attachments/assets/432a5cbb-7ad4-4c53-aa92-54e5da9c8356" />
Seems to have started happening since the Nodes 2.0 update (which i don't use).

**Comment by flyingshutter** [comment]
@alexopus So does that mean the mask editor works for you on the preview bridge?

**Comment by alexopus** [comment]
I don't use preview bridge, I only use image load node and edit mask on it. The New Mask editor works, but I prefer the old one.

**Comment by Lumiyumi** [comment]
Seems frontend 1.33.5 is the last version it was possible to use it with.

There it works when opening it from the node header utility bar.

**Comment by tester4488** [comment]
broken with comfyui-frontend-package-1.33.13 too

back to comfyui_frontend_package-1.32.9 and it work
<img width="1201" height="438" alt="Image" src="https://github.com/user-attachments/assets/b19c3921-4d21-42b3-b958-7cf38e3ef604" />

**Comment by rocky533** [comment]
Why was the other thread about this closed if it was not fixed and no info was told to us?

https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/1155#issuecomment-3618886181

Its still broke, if its going to be fixed, or if comfy itself needs to fix something i dont know but closing a topic with zero resolutions seems silly.  

I use preview bridge daily to edit masks, currently i am just previewing the image and then clipspace coping the the mask to a load image node to edit it.

Can we just get an answer as to what is going on here?

**Comment by flyingshutter** [comment]
@rocky533 Off topic: 
if you look again at 1155, you will notice that the issue was closed by the same person that opened it. Which is totally fine. You know how to open an issue. I did open an issue. This is free open source software. If anyone finds the solution to the issue, it will get fixed. If not, then not. I tried, but don't understand the issue. You are not entitled to an answer by anyone. Your post contributes nothing to the issue. This is not the place for rants but for exchanging info about the issue.

**Comment by rocky533** [comment]
I asked why it was closed, i did not blame anyone for doing it. i asked why.  I did not know who closed it, or cared. I was looking for an answer.

Good luck with your crap bro, second time you have been a dick to me for reporting something or trying to help to find a solution. 

I did not be an ass hole, you took it that way....  Read my posts again... and again if you dont get it. Get your panties out of that bunch.  I respect you for doing this for free, i do the fucking same thing with workflows so dont patronize me.  

Your nodes are broken, i was trying to fucking help.

**Comment by tester4488** [comment]
comfyui-frontend-package==1.34.8 same problem

**Comment by Lumiyumi** [comment]
an easy bandaid fix, that will make it partially function for people waiting:

in __init__.py rename the node:
line 193 "PreviewBridge": PreviewBridge, # noqa: F405

to as an example:

line 193 "PreviewBridgeFIX": PreviewBridge, # noqa: F405

While using it, whenever you want to make a new mask, empty the string or right click and fix node (recreate),

**Comment by without-ordinary** [comment]
> I asked why it was closed, i did not blame anyone for doing it. i asked why. I did not know who closed it, or cared. I was looking for an answer.

Because the person that opened that issue closed it after resolving it for themselves. Github shows who closed an issue and that user left a comment over there stating why. https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/1155#issuecomment-3618748376

The issue creator (a random user like you) has the ability to open and close their own issues. A reason is not required, only pressing that button.

**Comment by novikooff** [comment]
It would seem that the Mask Editor is trying to get the image at a temporary address, but the ComfyUI server does not find it.

<img width="1581" height="633" alt="Image" src="https://github.com/user-attachments/assets/9968f988-be1c-471c-9e03-bb5b0b62f8a8" />

**Comment by edicam** [comment]
> Why was the other thread about this closed if it was not fixed and no info was told to us?
> 
> [#1155 (comment)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/1155#issuecomment-3618886181)

I opened and closed #1155.
It was closed for two reasons : 
- It was solved downgrading frontend, as related on post;
- This is a clear indication that the issue is not related to Impact Pack, it's a frontend issue. Please, check https://github.com/Comfy-Org/ComfyUI_frontend/issues/7437

There is no reason to maintain an open issue for an issue not related to the node. You should close this issue and redirect your efforts to the frontend branch.

**Comment by without-ordinary** [comment]
> There is no reason to maintain an open issue for an issue not related to the node. You should close this issue and redirect your efforts to the frontend branch.

Its highly probable with all the random changes done in the frontend with the unfinished Nodes v2 (even with v2 not being enabled), that there may be some changes required by custom nodes to function again in the legacy UI. For sure there is going to be changes required for to make custom UIs work again Nodes v2, but v2 is quite unstable and unusable currently.

Even if that is not the case for this issue, its still a good idea to have an open issue here for SEO to track the status of the issue upstream; may I call your attention to the multiple duplicates already for this issue. 😆

**Comment by akawana** [comment]
@ltdrdata 

Suggestion:

Remove any dependency on string widget image as a key. I'm not sure why you need it, but If any internal map is needed, index it by unique_id.

You are saving preview in temp/PreviewBridge/..., always return for the mask editor only a ui_item in the format { filename, subfolder: 'PreviewBridge', type: 'temp' }.

like in your code

            ui_item = {
                "images": [
                    {
                        "filename": preview_filename,
                        "subfolder": preview_subfolder,
                        "type": preview_type,
                    }
                ]
            }

**Comment by kajan988** [comment]
Although I am not a specialist, it seems to me that the identifiers are not correct

dont work

<img width="390" height="85" alt="Image" src="https://github.com/user-attachments/assets/f3d53b59-51d7-43e6-a658-c9c8cca94420" />

https://github.com/user-attachments/assets/1e0f6357-9473-4c99-8196-dc395ce3f9ff

---------------------------------------------------------------- 

work only frontend=1.33.5 (or lower)

<img width="381" height="81" alt="Image" src="https://github.com/user-attachments/assets/e75a53e7-2377-49ea-aa03-352e96c8bb2f" />

https://github.com/user-attachments/assets/f80fbb82-e3d8-47b0-82dc-246feb96f069

**Comment by flyingshutter** [comment]
Workaround: Since https://github.com/Comfy-Org/ComfyUI_frontend/pull/7762

Setup ComfyUI to use the old (deprecated) mask editor
<img width="678" height="262" alt="Image" src="https://github.com/user-attachments/assets/d02d3d0c-50cc-47fd-8969-0e0dec8099c3" />

Select Preview Bridge and click the mask button:
<img width="373" height="426" alt="Image" src="https://github.com/user-attachments/assets/f96f3a29-8e68-45b5-803f-a8dede7e3b77" />

Do **NOT**: Right click image in the Preview Bridge -> Open in Mask Editor | Image Canvas

Windows Portable Package
ComfyUI version: 0.6.0
ComfyUI frontend version: 1.35.9

**Comment by kajan988** [comment]
> Workaround: Since [Comfy-Org/ComfyUI_frontend#7762](https://github.com/Comfy-Org/ComfyUI_frontend/pull/7762)
> 
> Setup ComfyUI to use the old (deprecated) mask editor <img alt="Image" width="678" height="262" src="https://private-user-images.githubusercontent.com/9995570/530975951-d02d3d0c-50cc-47fd-8969-0e0dec8099c3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjcxMDE4OTUsIm5iZiI6MTc2NzEwMTU5NSwicGF0aCI6Ii85OTk1NTcwLzUzMDk3NTk1MS1kMDJkM2QwYy01MGNjLTQ3ZmQtODk2OS0wZTBkZWM4MDk5YzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMzBUMTMzMzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA1MWNlZDVjMjdjYTExZjUyOThiMjFlZTkwZTcyMWEwOTUwM2IyNGY1OWQ4OGJiOTRkYWM3ZThkYTk1ZTVhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yihOiZHWVkXwebcMvHjQlV8eCF4QQ0gXnonu5X0ZMnY">
> 
> Select Preview Bridge and click the mask button: <img alt="Image" width="373" height="426" src="https://private-user-images.githubusercontent.com/9995570/530975377-f96f3a29-8e68-45b5-803f-a8dede7e3b77.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjcxMDE4OTUsIm5iZiI6MTc2NzEwMTU5NSwicGF0aCI6Ii85OTk1NTcwLzUzMDk3NTM3Ny1mOTZmM2EyOS04ZTY4LTQ1YjUtODAzZi1hOGRlZGU3ZTNiNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMzBUMTMzMzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE4NTQ4NWY0ODQxMzkyZjlkZGY2ZTdlZGJkMjMwZjVkYTNhNTk1ZTc5ODY0ZDZmYjgwOGViNjFlZWNjMDViYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AS5XEaQ0XdJFpmj_mIxIGKFATEfh6ynFJ71acCShqVo">
> 
> Do **NOT**: Right click image in the Preview Bridge -> Open in Mask Editor | Image Canvas

In frontend version 1.33.5, it works with the normal new mask menu, with or without right-click, it makes no difference.

The problem is clearly not with this switch and not with right-click.

And one more clarification:
the mask editor in the latest Comfy and the new frontend does not have a switch to the old editor.

**Comment by flyingshutter** [comment]
@kajan988 For reference, I am on:
Windows Portable Package
ComfyUI version: 0.6.0
ComfyUI frontend version: 1.35.9

**Comment by kajan988** [comment]
> [@kajan988](https://github.com/kajan988) For reference, I am on: Windows Portable Package ComfyUI version: 0.6.0 ComfyUI frontend version: 1.35.9

<img width="392" height="83" alt="Image" src="https://github.com/user-attachments/assets/8fdf576d-d28b-4339-b7f2-592a3e2bc896" />

<img width="1092" height="496" alt="Image" src="https://github.com/user-attachments/assets/72120a80-f28c-4183-92d4-7d695ea04a95" />

frontend 1.33.5  bridge works with "new mask editor"=on

**Comment by flyingshutter** [comment]
@kajan988 so to summarize:
- frontend 1.33.5 : Preview bridge mask editing works with "new mask editor"=on
- frontend v1.35.9 (which is currently used with ComfyUI master): "new mask editor"=on doesn't work anymore. Workaround = use the old mask editor, which is deprecated but still accessible 
- frontend v1.37.0 : Workaround not usable anymore, as old mask editor finally removed

(I found the right click / context menu thing was due to me not using "Nodes 2.0" at the time of testing)

**Comment by kajan988** [comment]
@flyingshutter 
Yeah.  As far as I understand, the front-end developers are dealing with this problem. 
https://github.com/Comfy-Org/ComfyUI_frontend/pull/7762

**Comment by flyingshutter** [comment]
Update:
The issue is solved with ComfyUI_frontend v1.37.1    (
ComfyUI master is using 1.35.9

I will close the issue when master is on >=v1.37.1

(if you are affected and want to have the latest frontend version, add
`--front-end-version Comfy-Org/ComfyUI_frontend@latest`
to your ComfyUI Launch script)

**Comment by treeshark12** [comment]
Not solved as far as I can see, indeed it has been removed from the impat pack altogether on th comfy cloud.

**Comment by kajan988** [comment]
> Not solved as far as I can see, indeed it has been removed from the impat pack altogether on th comfy cloud.

Its work. Since frontend 1.36.1. It works for me now with all the latest versions of Comfi and Frontend

**Comment by grancook** [comment]
Finally,!!   it works.
     Thank you

**Comment by flyingshutter** [comment]
Just updated ComfyUI. 
ComfyUI master is on frontend 1.37.11
Latest CofyUI Release v0.10.0 is on frontend v1.36.14
Mask editor works.
Closing issue.
