### ISSUE TITLE
ImpactMakeImageList stopped working

### ISSUE THREAD

**Issue by alexopus** [ltdrdata/ComfyUI-Impact-Pack#121]
I updated to f09159a96efea40929531bac68df998645bae979 today and the ImpactMakeImageList only accepts the first input now. The slot for the second input appears, but dragging anything to it does nothing.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/7627dbaa-4f89-43f1-ac3e-8bba29a3d764)

**Comment by ltdrdata** [comment]
This is fixed on bb783d4947546d53a1912e2d28ca62e6ab9624ee

**Comment by alexopus** [comment]
Something is still wrong - I cannot build a new MakeImageList from scratch - it still refuses the second input.

**Comment by ltdrdata** [comment]
> Something is still wrong - I cannot build a new MakeImageList from scratch - it still refuses the second input.

It could possibly be conflicting with a certain custom node. Please open the browser's dev tools and check for any error messages that may be occurring.

**Comment by alexopus** [comment]
There are no new errors occuring when I drag in a second image input. There were some present since Comfy launch however, not sure if related:

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/95368d7c-dc61-4eef-aa1c-2a829550cad3)

NestedNodeBuilder is an extension I had previously but removed sometime last week.

I also tried uninstalling pythongosssss/ComfyUI-Custom-Scripts, but that did not fix MakeImageList.

**Comment by alexopus** [comment]
Note: MakeImageList works fine if I revert to 75173d0c1bd2885ff45eef7e847bec48b713fd49.

**Comment by alexopus** [comment]
I did a fresh ComfyUI install with Manager & ImpactPack being the only custom nodes.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/2d2d737d-78fc-4fec-ba07-08246d9c347f)

It is still not accepting second input :/

**Comment by ltdrdata** [comment]
[impact-pack.js.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12440721/impact-pack.js.txt)

Download this and rename it to impact-pack.js, then try overwriting the files in ComfyUI-Impact-Pack/js directory with it. Then, restart and refresh your browser, press "export log" in the settings after refreshing, save it, and please attach it here.


![log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/6a3bf10d-6848-4608-a873-93aa6bde5513)

**Comment by alexopus** [comment]
<details>

<summary>comfyui-logs-1692985887285.json</summary>

```json
[
	{
		"source": "ComfyUI.Logging",
		"type": "debug",
		"timestamp": "2023-08-25T17:50:59.487Z",
		"message": {
			"UserAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"
		}
	},
	{
		"source": "ComfyUI.Logging",
		"type": "debug",
		"timestamp": "2023-08-25T17:50:59.502Z",
		"message": {
			"system": {
				"os": "nt",
				"python_version": "3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]",
				"embedded_python": false
			},
			"devices": {
				"name": "cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync",
				"type": "cuda",
				"index": 0,
				"vram_total": 8589279232,
				"vram_free": 7458521088,
				"torch_vram_total": 0,
				"torch_vram_free": 0
			}
		}
	},
	{
		"source": "Comfy.App",
		"type": "debug",
		"timestamp": "2023-08-25T17:50:59.502Z",
		"message": {
			"Extensions": [
				"/extensions/core/clipspace.js",
				"/extensions/core/colorPalette.js",
				"/extensions/core/contextMenuFilter.js",
				"/extensions/core/dynamicPrompts.js",
				"/extensions/core/editAttention.js",
				"/extensions/core/invertMenuScrolling.js",
				"/extensions/core/keybinds.js",
				"/extensions/core/linkRenderMode.js",
				"/extensions/core/maskeditor.js",
				"/extensions/core/nodeTemplates.js",
				"/extensions/core/noteNode.js",
				"/extensions/core/rerouteNode.js",
				"/extensions/core/saveImageExtraOutput.js",
				"/extensions/core/slotDefaults.js",
				"/extensions/core/snapToGrid.js",
				"/extensions/core/uploadImage.js",
				"/extensions/core/widgetInputs.js",
				"/extensions/ComfyUI-Impact-Pack/comboBoolMigration.js",
				"/extensions/ComfyUI-Impact-Pack/impact-pack.js",
				"/extensions/ComfyUI-Impact-Pack/impact-sam-editor.js",
				"/extensions/ComfyUI-Manager/comfyui-manager.js"
			]
		}
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:50:59.642Z",
		"message": "[DEBUG] onConnectionsChange: 1, 0, true / undefined"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] onConnectionsChange: 1, 0, true / {\"id\":3,\"type\":\"IMAGE\",\"origin_id\":1,\"origin_slot\":0,\"target_id\":3,\"target_slot\":0,\"_data\":null,\"_pos\":{\"0\":0,\"1\":0}}"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] STEP2 IMAGE"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] STEP3 [{\"name\":\"image1\",\"type\":\"IMAGE\",\"link\":3,\"label\":\"image1\"}]"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] STEP4 true, undefined, undefined, undefined"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] STEP5 1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] STEP5-1 image1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] STEP5-1-1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] STEP6 1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] STEP7 image1, undefined / 3"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] STEP7 : image2 / IMAGE"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] STEP8: undefined"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:04.570Z",
		"message": "[DEBUG] STEP9\n\n"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.102Z",
		"message": "[DEBUG] onConnectionsChange: 1, 1, true / {\"id\":4,\"type\":\"IMAGE\",\"origin_id\":2,\"origin_slot\":0,\"target_id\":3,\"target_slot\":1,\"_data\":null,\"_pos\":{\"0\":0,\"1\":0}}"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.102Z",
		"message": "[DEBUG] STEP2 IMAGE"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.102Z",
		"message": "[DEBUG] STEP3 [{\"name\":\"image1\",\"type\":\"IMAGE\",\"link\":3,\"label\":\"image1\"},{\"name\":\"image2\",\"type\":\"IMAGE\",\"link\":4}]"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.102Z",
		"message": "[DEBUG] STEP4 true, undefined, undefined, undefined"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.102Z",
		"message": "[DEBUG] STEP4-1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.102Z",
		"message": "[DEBUG] STEP4-2 beforeRegisterNodeDef/nodeType.prototype.onConnectionsChange@http://127.0.0.1:8188/extensions/ComfyUI-Impact-Pack/impact-pack.js:294:40\nLGraphNode.prototype.connect@http://127.0.0.1:8188/lib/litegraph.core.js:4354:16\nLGraphCanvas.prototype.processMouseUp@http://127.0.0.1:8188/lib/litegraph.core.js:6720:54\nEventListener.handleEvent*LiteGraph.pointerListenerAdd@http://127.0.0.1:8188/lib/litegraph.core.js:14311:10\nLGraphCanvas.prototype.processMouseDown@http://127.0.0.1:8188/lib/litegraph.core.js:5845:14\n#addProcessMouseHandler/LGraphCanvas.prototype.processMouseDown@http://127.0.0.1:8188/scripts/app.js:703:37\nEventListener.handleEvent*LiteGraph.pointerListenerAdd@http://127.0.0.1:8188/lib/litegraph.core.js:14311:10\nLGraphCanvas.prototype.bindEvents@http://127.0.0.1:8188/lib/litegraph.core.js:5612:13\nLGraphCanvas.prototype.setCanvas@http://127.0.0.1:8188/lib/litegraph.core.js:5571:18\nLGraphCanvas@http://127.0.0.1:8188/lib/litegraph.core.js:5327:14\nsetup@http://127.0.0.1:8188/scripts/app.js:1063:33\nasync*@http://127.0.0.1:8188/:14:14\n"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.102Z",
		"message": "[DEBUG] STEP4-2-1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.102Z",
		"message": "[DEBUG] onConnectionsChange: 1, 1, false / {\"id\":4,\"type\":\"IMAGE\",\"origin_id\":2,\"origin_slot\":0,\"target_id\":3,\"target_slot\":1,\"_data\":null,\"_pos\":{\"0\":0,\"1\":0}}"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.102Z",
		"message": "[DEBUG] STEP2 IMAGE"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.102Z",
		"message": "[DEBUG] STEP3 [{\"name\":\"image1\",\"type\":\"IMAGE\",\"link\":3,\"label\":\"image1\"},{\"name\":\"image2\",\"type\":\"IMAGE\",\"link\":null}]"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP4 false, undefined, undefined, undefined"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP4-1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP4-2 beforeRegisterNodeDef/nodeType.prototype.onConnectionsChange@http://127.0.0.1:8188/extensions/ComfyUI-Impact-Pack/impact-pack.js:294:40\nLGraphNode.prototype.disconnectInput@http://127.0.0.1:8188/lib/litegraph.core.js:4602:11\nLGraphNode.prototype.removeInput@http://127.0.0.1:8188/lib/litegraph.core.js:3533:14\nbeforeRegisterNodeDef/nodeType.prototype.onConnectionsChange@http://127.0.0.1:8188/extensions/ComfyUI-Impact-Pack/impact-pack.js:299:30\nLGraphNode.prototype.connect@http://127.0.0.1:8188/lib/litegraph.core.js:4354:16\nLGraphCanvas.prototype.processMouseUp@http://127.0.0.1:8188/lib/litegraph.core.js:6720:54\nEventListener.handleEvent*LiteGraph.pointerListenerAdd@http://127.0.0.1:8188/lib/litegraph.core.js:14311:10\nLGraphCanvas.prototype.processMouseDown@http://127.0.0.1:8188/lib/litegraph.core.js:5845:14\n#addProcessMouseHandler/LGraphCanvas.prototype.processMouseDown@http://127.0.0.1:8188/scripts/app.js:703:37\nEventListener.handleEvent*LiteGraph.pointerListenerAdd@http://127.0.0.1:8188/lib/litegraph.core.js:14311:10\nLGraphCanvas.prototype.bindEvents@http://127.0.0.1:8188/lib/litegraph.core.js:5612:13\nLGraphCanvas.prototype.setCanvas@http://127.0.0.1:8188/lib/litegraph.core.js:5571:18\nLGraphCanvas@http://127.0.0.1:8188/lib/litegraph.core.js:5327:14\nsetup@http://127.0.0.1:8188/scripts/app.js:1063:33\nasync*@http://127.0.0.1:8188/:14:14\n"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP4-2-1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP5 1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP5-1 image1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP5-1-1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP6 1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP7 image1, undefined / 3"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP7 : image2 / IMAGE"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP8: undefined"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP9\n\n"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP5 1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP5-1 image1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP5-1-1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP6 1"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP7 image1, undefined / 3"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP7 : image2 / IMAGE"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP8: undefined"
	},
	{
		"source": "console",
		"type": "log",
		"timestamp": "2023-08-25T17:51:09.103Z",
		"message": "[DEBUG] STEP9\n\n"
	}
]
```

</details>

**Comment by ltdrdata** [comment]
> comfyui-logs-1692985887285.json

Do you use touch device instead of mouse?

**Comment by alexopus** [comment]
Nope, only mouse

**Comment by ltdrdata** [comment]
> Nope, only mouse

Anyway try this 05bbb58546ba14d17c1889c29e9756524a61204c
I'm not sure why, but for some reason, the mouse handling behavior in litegraph is acting differently. I made adjustments to correspond to that.

Don't forget the `git reset --hard` before update

**Comment by alexopus** [comment]
It is working again with that - the second input gets hooked! Thanks!

**Comment by ltdrdata** [comment]
> It is working again with that - the second input gets hooked! Thanks!

Thanks to your efforts, I was able to catch the bug. Thank you.
