### ISSUE TITLE
Switch Node not working

### ISSUE THREAD

**Issue by trashie65** [ltdrdata/ComfyUI-Impact-Pack#123]
after adding a switch node(any) when you fist connect a noddle the input says imput 1, after you connect the next imput shows also called imput 1 and you can't connect to it

**Comment by ltdrdata** [comment]
I'll patch when I get home

**Comment by ltdrdata** [comment]
This is fixed.

bb783d4947546d53a1912e2d28ca62e6ab9624ee

**Comment by tht78** [comment]
It increases the slot number correctly now but still does not accept a second connection/node input.

**Comment by ltdrdata** [comment]
> It increases the slot number correctly now but still does not accept a second connection/node input.

It could possibly be conflicting with a certain custom node. Please open the browser's dev tools and check for any error messages that may be occurring.

**Comment by tht78** [comment]
Possibly, but I disabled all other extensions besides the manager and impact-pack. Still not working. It could be my environment of course. If it works for you others, I will have to investigate that.

**Comment by trashie65** [comment]
It not working for me either same as tht78. cannot connect a second connection

**Comment by ltdrdata** [comment]
> Possibly, but I disabled all other extensions besides the manager and impact-pack. Still not working. It could be my environment of course. If it works for you others, I will have to investigate that.

Unfortunately, most custom nodes currently do not handle the disablement of the web extension properly. Please try removing all of them except for core and impact pack in /web/extensions.

**Comment by trashie65** [comment]
Ive removed all of the web extensions except core and impack pack and till you can't connect a second conection

**Comment by ltdrdata** [comment]
> Ive removed all of the web extensions except core and impack pack and till you can't connect a second conection

What is your browser?

**Comment by trashie65** [comment]
firefox

**Comment by trashie65** [comment]
how do i disable the extensions because when i open comfy it puts the extensions back into the web extensions folder...lol

**Comment by ltdrdata** [comment]
> how do i disable the extensions because when i open comfy it puts the extensions back into the web extensions folder...lol

just remove and refesh browser without restart ComfyUI

**Comment by ltdrdata** [comment]
> > how do i disable the extensions because when i open comfy it puts the extensions back into the web extensions folder...lol
> 
> just remove and refesh browser without restart ComfyUI

The recovering will be stopped if you disable the nodes.

**Comment by trashie65** [comment]
ok ive done what you say.. there is only core and impack pack in the web extensions folder .. refreshed the browser. still you can only connect 1 connection

**Comment by ltdrdata** [comment]
> ok ive done what you say.. there is only core and impack pack in the web extensions folder .. refreshed the browser. still you can only connect 1 connection

what node did you tried connect to switch node?

**Comment by trashie65** [comment]
SDXL Sampler v2(Searge) Latent Output. but it does not matter you get the same with any node

**Comment by ltdrdata** [comment]
> Searge

I am trying to reproduce...
Did you tried this?

![switch](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/4110ad6a-f7b8-45e7-8e98-27015d5563f8)

Is it possible to leave the currently installed version as it is and install a new one in a different folder just to test with the Impact Pack installed?

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/121#issuecomment-1693506755

If you also create a log file like this and send it to me, I will analyze it.

**Comment by ltdrdata** [comment]
Try this 05bbb58546ba14d17c1889c29e9756524a61204c

**Comment by trashie65** [comment]
It is working now, Thank you very much for your time and thank you for the impack pack, very helpful :)

**Comment by tht78** [comment]
Seems to be working in my installation also. Thank you for looking into this. Very useful node and extension as a whole.

**Comment by trashie65** [comment]
![missing nodes](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/45748708/cb98efaa-4b7c-4b53-a4fb-9fcf19ca185a)
After updating i now have to missing nodes in some of my workflows..     BboxDetectorForEach
    MMDetLoader, have they been removed or renamed? Please what should i use in there place

**Comment by ltdrdata** [comment]
> After updating i now have to missing nodes in some of my workflows.. BboxDetectorForEach MMDetLoader, have they been removed or renamed? Please what should i use in there place

https://www.youtube.com/watch?v=t-JjsEvPX7o

MMDetLoader was deprecated a long time ago. Since then, it has been replaced by MMDetectorProvider, and currently, the transition has been made from MMDet to UltralyticsDetectorProvider completely.

Here are the workflows and tutorials, so please refer to them.
https://github.com/ltdrdata/ComfyUI-extension-tutorials

**Comment by trashie65** [comment]
Ok thank you

**Comment by alessandroperilli** [comment]
Not sure if this is related, but I have an issue with this exact switch node in the following scenario: 

<img width="756" alt="Screenshot 2023-08-29 at 00 44 28" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/bad12f40-397b-472d-a843-1cfe47e61b51">

The switch (any) node receives 4 different input images from 4 different areas of the workflow below, and it passes the selected one to an upscaler. At any given time, only one of the four images has been generated. The other 3 inputs have nothing.

In this situation, the switch refuses to pass the available image, even if it has been correctly selected. 

The full workflow, to test it, is here: [https://perilli.com/ai/comfyui](https://perilli.com/ai/comfyui)

Is this the intended behaviour? If not, is it somehow connected to the issue? If not, I'll be happy to one a dedicated issue.

Thank you.

**Comment by ltdrdata** [comment]
This is related to the limitations of ComfyUI itself. Connected inputs are considered as the necessary inputs for executing that node, and if the inputs are incomplete, the switch node itself won't be executed by ComfyUI.

**Comment by alessandroperilli** [comment]
Thanks @ltdrdata, and thanks for the amazing nodes you have developed for the community so far. To not further pollute this issue, if anybody has a suggestion to solve the issue, please reach out in private.
