### ISSUE TITLE
`ImpactValueReceiver` is broken

### ISSUE THREAD

**Issue by mijuku233** [ltdrdata/ComfyUI-Impact-Pack#237]
After `ImpactValueReceiver` receives `value`, typ becomes `string` instead of `STRING`, so that `value` cannot be output, and an error is thrown when running again.

![send](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/89350747/bf8d243c-0811-4ace-8865-08e887c84288)

Error message:

> Prompt outputs failed validation
ImpactValueReceiver:
Value not in list: typ: 'string' not in ['STRING', 'INT', 'FLOAT', 'BOOLEAN']

**Comment by mijuku233** [comment]
One more thing to add, I used the `Primitive` node to temporarily solve the `typ` problem, and then created the iteration through [comfyui-job-iterator](https://github.com/ali1234/comfyui-job-iterator) , and then found that `ImpactValueReceiver` can only output `value` for the first iteration, and cannot output `value` for each iteration.

**Comment by ltdrdata** [comment]
This is fixed on 411522ef72856867de1ff3357e528a37b819d472.

**Comment by ltdrdata** [comment]
> One more thing to add, I used the `Primitive` node to temporarily solve the `typ` problem, and then created the iteration through [comfyui-job-iterator](https://github.com/ali1234/comfyui-job-iterator) , and then found that `ImpactValueReceiver` can only output `value` for the first iteration, and cannot output `value` for each iteration.

That means the value of the receiver has not changed.

**Comment by mijuku233** [comment]
@ltdrdata After the update, the problem that `ImpactValueReceiver` cannot output value in each iteration is still not solved.

**Comment by ltdrdata** [comment]
What is your workflow?

**Comment by mijuku233** [comment]
> What is your workflow?

![workflow (2)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/89350747/ffe518b9-c968-488b-8ee6-49850d5b33bd)

**Comment by ltdrdata** [comment]
> > What is your workflow?
> 
> ![workflow (2)](https://user-images.githubusercontent.com/89350747/277169290-ffe518b9-c968-488b-8ee6-49850d5b33bd.png)

I meant json file.

**Comment by mijuku233** [comment]
This image contains workflow information, but I still uploaded a zip file containing json

The json was corrupted for some unknown reason, I have re-uploaded it
[valueR.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13063414/valueR.zip)

**Comment by mijuku233** [comment]
@ltdrdata 
Even if iteration is performed by setting `batch count`, `ImpactValueReceiver` still cannot output `value`.

![send (5)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/89350747/f3aa9194-bb6f-425d-af75-994d9318620c)


However, what is interesting is that in `auto queue` mode, `ImpactValueReceiver` outputs `value` normally.

![send (6)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/89350747/1a63c362-cb69-4b95-82ea-b5488f3bc89b)

**Comment by mijuku233** [comment]
@ltdrdata 
When some nodes are running, `ImpactValueReceiver` will be prevented from continuously outputting `value`, even if it is not associated with `ImpactValueSend`, such as `wd14 tagger`

![send (7)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/89350747/c9641a83-0c94-4fb9-a474-b8ceb76632be)


However, even if `wd14 tagger` is disabled, `ImpactValueReceiver` still cannot completely output the `value` of all iterations

![send (8)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/89350747/de5ad9ea-e8fd-422a-b785-c8f3df607047)

The zip below is the workflow I use to test bugs：
[bug02.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13069655/bug02.zip)

**Comment by ltdrdata** [comment]
The issue is that the timing of putting the queue does not match the timing of sending it to the sender. 
Configuring `Impact Pack`'s logics nodes by placing a node called `Queue Trigger` behind the Receiver instead of the job iterator would be helpful.

**Comment by mijuku233** [comment]
I just tried `Queue Trigger` and it keeps iterating until I close it manually, just like `auto queue`. But that's not what I need, I just need it to iterate a certain number of times and then stop, how can I achieve it with `Queue Trigger`?

**Comment by mijuku233** [comment]
There is another problem. I only need a part of the nodes in the workflow to iterate. It seems that `Queue Trigger` cannot achieve this because it makes the entire workflow iterate.

**Comment by ltdrdata** [comment]
> I just tried `Queue Trigger` and it keeps iterating until I close it manually, just like `auto queue`. But that's not what I need, I just need it to iterate a certain number of times and then stop, how can I achieve it with `Queue Trigger`?

You should handle by logic.

**Comment by mijuku233** [comment]
> > I just tried `Queue Trigger` and it keeps iterating until I close it manually, just like `auto queue`. But that's not what I need, I just need it to iterate a certain number of times and then stop, how can I achieve it with `Queue Trigger`?
> 
> You should handle by logic.



I don't know how to implement it with logic, and I need to split a batch midway into iterations equal to the batch size, there can only be one queue, Queue Trigger increases the queue, it cannot replace[ comfyui-job-iterator ](https://github.com/ali1234/comfyui-job-iterator)to solve the problem.

**Comment by mijuku233** [comment]
@ltdrdata 
I use `Queue Trigger` to iterate based on logic, but the output results are still wrong.
The following is the incorrect result obtained using `Queue Trigger` iteration:
![que1 2023-10-25 033507](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/89350747/3bb1a18e-2b34-469d-b7ed-a01131a1bbbc)
And the correct result should be like this:
![queue2 2023-10-25 033619](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/89350747/64289c91-c206-45b4-ac97-db91a52bb44b)
workflow：
[queue.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13126908/queue.json)


In addition, the Queue Trigger node is really good when used with logic. For this node, I have an idea to make it easier to use.
Thank you so much for making these awesome nodes!

**Comment by ltdrdata** [comment]
In fact, the purpose of signal input/output is not data transfer but to control the order of execution. `Queue Trigger` was added along with `Set Widget Value` and `Set Mute State` to implement the loop functionality.

I recommend take a look at them, also.

**Comment by mijuku233** [comment]
@ltdrdata 
The key to the problem is not how to implement the loop. I have many ways to implement the loop, including using the nodes you mentioned.
What I'm trying to say is that these nodes that send information are buggy and don't work properly in a loop job.
Not just `send value`, all nodes that can send information have the same error, such as the following, `Set Widget Value`, `send image`, `send latent`.

**Comment by mijuku233** [comment]
@ltdrdata 
My workflow works fine by using automatic loops to avoid bugs, so the problem should be focused on these buggy nodes.
These sending nodes are really cool, so I'm really hoping that the looping bug can be fixed.

**Comment by ltdrdata** [comment]
> @ltdrdata My workflow works fine by using automatic loops to avoid bugs, so the problem should be focused on these buggy nodes. These sending nodes are really cool, so I'm really hoping that the looping bug can be fixed.

That's not a bug. That is a limitation.

It happened because the workflow did not take into account the execution order. When you trigger the Queue, the current value of the widget at the front goes into the prompt. 

The Value Sender dynamically updates the widget value while the workflow is running. If the Queue Trigger is either the same as or in front of the Value Sender, a race condition can occur, and it cannot be guaranteed which value will be entered at the queue prompt moment.

When using the existing Value Sender, there was no way to guarantee this order. By adding signal output, we enabled the configuration of the workflow as follows.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/4edb34b8-3d72-4d8e-a781-03df46cb0f25)

In the nodes I provide, inputs or outputs labeled `signal` are not meant for conveying actual meaningful values but are intended for controlling the execution order.

**Comment by ltdrdata** [comment]
I just added `signal` input, too.
Now you can chainning Value Senders.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/5b75c650-3085-4e27-b026-f1d56f8d4b45)
