### ISSUE TITLE
Mask Subtraction Issue: RuntimeError: The size of tensor a (1024) must match the size of tensor b (8) at non-singleton dimension 1

### ISSUE THREAD

**Issue by ckao10301** [ltdrdata/ComfyUI-Impact-Pack#433]
When no object is detected, the output segs is 64x64. It needs to match the size of the input image dimensions. This causes issues with mask subtraction.

<img width="808" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129625358/a7ff1777-2c29-4dc6-aca6-005ae0a877b0">

**Comment by ckao10301** [comment]
Reproduce:

[mask subtract workflow.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13927553/mask.subtract.workflow.json)
![ComfyUI_temp_ppzue_00001_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129625358/92a252f2-d54c-44be-95af-aa68594dcb81)

**Comment by ltdrdata** [comment]
This is fixed on v4.66.1

**Comment by ckao10301** [comment]
I'm just updated to v4.66.1

<img width="360" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129625358/b5a6c0d4-ceff-45a3-b27e-e33825d141f4">

But I'm still getting the same issue:

<img width="949" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129625358/b2dcb294-482e-4237-af46-15dbd85e8dc9">

**Comment by ltdrdata** [comment]
This is fixed, again.

**Comment by ckao10301** [comment]
confirmed. thank you so much!
