### ISSUE TITLE
SAM Detector selected mask whole image offset

### ISSUE THREAD

**Issue by gitST2020** [ltdrdata/ComfyUI-Impact-Pack#836]
When trying to select a mask by using "Open in SAM Detector", the selected mask is warped and the wrong size - before saving to the node.  It looks like the whole image is offset.
I have the most up-to-date ComfyUI and ComfyUI-Impact-Pack.
I have installed ComfyUI from scratch and this is the only custom node I have installed.

Image attached:

![SAM Detector image mask overlay off](https://github.com/user-attachments/assets/8bd979da-3684-4ccb-b243-20b063ddc038)

D:\ComfyUI>call D:\Comfyui_env\Scripts\activate.bat
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-29 11:40:19.101588
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\Comfyui_env\Scripts\python.exe
** ComfyUI Path: D:\ComfyUI
** Log path: D:\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   1.5 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 23028 MB, total RAM 196371 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[Prompt Server] web root: D:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.5.1
Adding extra search path checkpoints W:/SD\models/Stable-diffusion
Adding extra search path loras W:/SD\models/Lora
Adding extra search path loras W:/SD\models/LyCORIS
Adding extra search path checkpoints path/to/comfyui/models/checkpoints/
Adding extra search path clip path/to/comfyui/models/clip/
Adding extra search path clip_vision path/to/comfyui/models/clip_vision/
Adding extra search path configs path/to/comfyui/models/configs/
Adding extra search path controlnet path/to/comfyui/models/controlnet/
Adding extra search path diffusion_models path/to/comfyui/models/diffusion_models
Adding extra search path diffusion_models path/to/comfyui/models/unet
Adding extra search path embeddings path/to/comfyui/models/embeddings/
Adding extra search path loras path/to/comfyui/models/loras/
Adding extra search path upscale_models path/to/comfyui/models/upscale_models/
Adding extra search path vae path/to/comfyui/models/vae/
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2874 [20a560eb] | Released on '2024-11-29'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\custom_nodes\websocket_image_save.py
   0.3 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Setting output directory to: X:\ComfyOutput
Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
Update custom node 'ComfyUI Impact Pack'
Update: ['https://github.com/ltdrdata/ComfyUI-Impact-Pack']
CUSTOM NODE PULL: None
Update was successful.
After restarting ComfyUI, please refresh the browser.

Restarting... [Legacy Mode]

[START] Security scan
Press any key to continue . . . [DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-29 11:40:51.378873
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\Comfyui_env\Scripts\python.exe
** ComfyUI Path: D:\ComfyUI
** Log path: D:\ComfyUI\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

Install: pip packages for 'D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
   [SKIP] Downgrading pip package isn't allowed: scipy (cur=1.14.1)
Install: install script for 'D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
[!]
[!] [bold yellow]WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `D:\ComfyUI\models` as the ComfyUI path.[/bold yellow]
 ### ComfyUI-Impact-Pack: Check dependencies
 ### ComfyUI-Impact-Pack: Updating subpack
 [Impact Pack] EXECUTE: ['D:\\Comfyui_env\\Scripts\\python.exe', 'install.py'] in 'D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
 ### ComfyUI-Impact-Pack: Check basic models

[ComfyUI-Manager] Startup script completed.
#######################################################################

Prestartup times for custom nodes:
   7.5 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 23028 MB, total RAM 196371 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[Prompt Server] web root: D:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.5.1
Adding extra search path checkpoints W:/SD\models/Stable-diffusion
Adding extra search path loras W:/SD\models/Lora
Adding extra search path loras W:/SD\models/LyCORIS
Adding extra search path checkpoints path/to/comfyui/models/checkpoints/
Adding extra search path clip path/to/comfyui/models/clip/
Adding extra search path clip_vision path/to/comfyui/models/clip_vision/
Adding extra search path configs path/to/comfyui/models/configs/
Adding extra search path controlnet path/to/comfyui/models/controlnet/
Adding extra search path diffusion_models path/to/comfyui/models/diffusion_models
Adding extra search path diffusion_models path/to/comfyui/models/unet
Adding extra search path embeddings path/to/comfyui/models/embeddings/
Adding extra search path loras path/to/comfyui/models/loras/
Adding extra search path upscale_models path/to/comfyui/models/upscale_models/
Adding extra search path vae path/to/comfyui/models/vae/
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2874 [20a560eb] | Released on '2024-11-29'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\custom_nodes\websocket_image_save.py
   0.3 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Setting output directory to: X:\ComfyOutput
Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[INFO] ComfyUI-Impact-Pack: Loading SAM model 'D:\ComfyUI\models'
[INFO] ComfyUI-Impact-Pack: SAM model loaded.
[INFO] ComfyUI-Impact-Pack: Loading SAM model 'D:\ComfyUI\models'
[INFO] ComfyUI-Impact-Pack: SAM model loaded.
[INFO] ComfyUI-Impact-Pack: Loading SAM model 'D:\ComfyUI\models'
[INFO] ComfyUI-Impact-Pack: SAM model loaded.
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]

**Comment by adamjen** [comment]
I have the same "sam" issue for a few weeks now. 

[2024-11-30 15:04:16.718] ### Loading: ComfyUI-Impact-Pack (V7.12)
[2024-11-30 15:04:16.719] [Impact Pack] Wildcards loading done.
[2024-11-30 15:04:16.723] ### Loading: ComfyUI-Inspire-Pack (V1.7)
[2024-11-30 15:04:16.819] Total VRAM 16380 MB, total RAM 31850 MB
[2024-11-30 15:04:16.819] pytorch version: 2.5.1+cu124
[2024-11-30 15:04:16.819] xformers version: 0.0.28.post3
[2024-11-30 15:04:16.866] ### Loading: ComfyUI-Manager (V2.53)
[2024-11-30 15:04:16.950] ### ComfyUI Revision: 2856 [ab885b33] | Released on '2024-11-23'

**Comment by ltdrdata** [comment]
It seems that the recent update to the front has broken compatibility. A patch is planned.

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by gitST2020** [comment]
I see that the offset of the mask is gone - but I still get the wrong part of the image selected which I click in a space.  I think the point and click is also offset.  Look at the attached - you'll see the blue dots and only a portion of the image selected.
![Screenshot 2024-12-11 231607](https://github.com/user-attachments/assets/eb23837e-7182-4682-a774-b50e16958705)
![Screenshot 2024-12-11 231447](https://github.com/user-attachments/assets/9068151d-8132-49d4-9570-f9eb87ca7185)
