### ISSUE TITLE
[Bug]: The first link you connect to Switch (Any) isn't of the right type

### ISSUE THREAD

**Issue by LukeG89** [ltdrdata/ComfyUI-Impact-Pack#851]
There is a problem with Switch (Any). As said in the title, the first link you connect isn't of the right type. Plus, it keeps the "dot" inside the first input like it's optional, but not the other ones (especially the last one)

In this video I'm using the current ComfyUI frontend (1.4.13)

https://github.com/user-attachments/assets/0e582117-8cf2-4f80-b256-56c4c440f31c

~I think this problem also leads to corrupted linking data (reported by rgthree feature), it happened a couple of times with a workflow. Maybe it's related to this issue, but to be honest I have not investigated, I just stopped using the switch.~
Nevermind about that, I tried to reproduce the issue, but everything seems to work fine (maybe it has been fixed with another commit or something, I don't know) 

## Debug logs:
```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-11 17:15:58.711234
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\python_embeded\python.exe
** ComfyUI Path: E:\ComfyUI
** Log path: E:\comfyui.log

Prestartup times for custom nodes:
   2.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.6.0.dev20241204+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI\web
### Loading: ComfyUI-Impact-Pack (V8.0.1)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.55.4)
### ComfyUI Version: v0.3.7-14-g7a7efe84 | Released on '2024-12-11'

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI\custom_nodes\loadImageWithSubfolders.py
   0.1 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.3 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by LukeG89** [comment]
The same "first link" issue is present in `Inversed Switch (Any)`

![image](https://github.com/user-attachments/assets/8d414ad9-f5be-4a45-bb61-51f972f23e9c)

**Comment by ltdrdata** [comment]
> The same "first link" issue is present in `Inversed Switch (Any)`
> 
> ![image](https://private-user-images.githubusercontent.com/161304036/391243535-8d414ad9-f5be-4a45-bb61-51f972f23e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTg4ODEsIm5iZiI6MTczNDYxODU4MSwicGF0aCI6Ii8xNjEzMDQwMzYvMzkxMjQzNTM1LThkNDE0YWQ5LWY1YmUtNGE0NS1iYjYxLTUxZjk3MmYyM2U5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQxNDI5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjljODczMjgzZmI5NmQ2OGU2YTczNDNkNTA0YTViZDE1YzczYmUzMDViZjdjMjNmNjA4OTE4ZDlhYmJiMDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IT90OWS1NSUoHD2dBkPeFFlAjENsLPHJ_-q4Mwn7xM4)

This is fixed.

**Comment by LukeG89** [comment]
@ltdrdata I still have the issue 
ComfyUI-Impact-Pack (V8.1.2)


https://github.com/user-attachments/assets/46917830-9d90-41d3-8a74-a9e4ab41d715

**Comment by ltdrdata** [comment]
> @ltdrdata I still have the issue ComfyUI-Impact-Pack (V8.1.2)
> 
>  Same-issue.mp4



> There is a problem with Switch (Any). As said in the title, the first link you connect isn't of the right type. Plus, it keeps the "dot" inside the first input like it's optional, but not the other ones (especially the last one)
> 
> In this video I'm using the current ComfyUI frontend (1.4.13)
> 
>  Switch-Test.mp4 
> ~I think this problem also leads to corrupted linking data (reported by rgthree feature), it happened a couple of times with a workflow. Maybe it's related to this issue, but to be honest I have not investigated, I just stopped using the switch.~ Nevermind about that, I tried to reproduce the issue, but everything seems to work fine (maybe it has been fixed with another commit or something, I don't know)

Ah, I was mistaken about the issue. The issue I fixed was related to `select_on_prompt` and has nothing to do with this one.

However, I don't understand the issue you're pointing out. The moment you make the first connection with an image, the switch's `input` and `output` are bound to `IMAGE` type (sky blue dot) correctly.

**Comment by LukeG89** [comment]
> However, I don't understand the issue you're pointing out. The moment you make the first connection with an image, the switch's input and output are bound to IMAGE type (sky blue dot) correctly.

Yes, but the first link is not of the correct type. Not a big issue though

**Comment by ltdrdata** [comment]
> > However, I don't understand the issue you're pointing out. The moment you make the first connection with an image, the switch's input and output are bound to IMAGE type (sky blue dot) correctly.
> 
> Yes, but the first link is not of the correct type. Not a big issue though

Oh do you referring connection color?

**Comment by LukeG89** [comment]
Yep

**Comment by LukeG89** [comment]
Maybe the "Bug" tag for that was too much 😅

**Comment by LukeG89** [comment]
Closing this issue since it's just a minor aesthetic things that can be fixed by connecting the first link (to make the input of the correct type), disconnecting and reconnecting it again.
